version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
  rabbit:
    image: rabbitmq:3.7
  api:
    container_name: api
    build:
      context: .
    environment:
      - DB_URL=mongodb://mongodb:27017
    ports:
      - 9090:9090
    depends_on:
      - mongodb
      - rabbit
  worker:
    container_name: worker
    build:
      context: .
    environment:
      - BROKER_URL=pyamqp://guest@rabbit:5672
      - DB_URL=mongodb://mongodb:27017
    entrypoint: supervisord
    command: -c supervisord.conf
    links:
      - rabbit
    depends_on:
      - rabbit
      - mongodb
